<a href="https://colab.research.google.com/github/ichaelo/ML-LAB_1/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/dataset/global-data-on-sustainable-energy.csv")
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [ ]:
# Columns
df.columns

Index(['Entity', 'Year', 'Access to electricity (% of population)',
       'Access to clean fuels for cooking',
       'Renewable-electricity-generating-capacity-per-capita',
       'Financial flows to developing countries (US $)',
       'Renewable energy share in the total final energy consumption (%)',
       'Electricity from fossil fuels (TWh)', 'Electricity from nuclear (TWh)',
       'Electricity from renewables (TWh)',
       'Low-carbon electricity (% electricity)',
       'Primary energy consumption per capita (kWh/person)',
       'Energy intensity level of primary energy (MJ/$2017 PPP GDP)',
       'Value_co2_emissions_kt_by_country',
       'Renewables (% equivalent primary energy)', 'gdp_growth',
       'gdp_per_capita', 'Density\n(P/Km2)', 'Land Area(Km2)', 'Latitude',
       'Longitude'],
      dtype='object')

In [ ]:
# First five
df.head(5)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [ ]:
df.tail(5)

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.6802,10.00,11020.00046,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.0115,9.51,10340.00015,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.9858,9.83,12380.00011,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.6553,10.47,11760.00023,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.1318,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [ ]:
df.describe()

,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Land Area(Km2),Latitude,Longitude
count,3649.000000,3639.000000,3480.000000,2718.000000,1.560000e+03,3455.000000,3628.000000,3523.000000,3628.000000,3607.000000,3649.000000,3442.000000,3.221000e+03,1512.000000,3332.000000,3367.000000,3.648000e+03,3648.000000,3648.000000
mean,2010.038367,78.933702,63.255287,113.137498,9.422400e+07,32.638165,70.365003,13.450190,23.968010,36.801182,25743.981745,5.307345,1.598665e+05,11.986707,3.441610,13283.774348,6.332135e+05,18.246388,14.822695
std,6.054228,30.275541,39.043658,244.167256,2.981544e+08,29.894901,348.051866,73.006623,104.431085,34.314884,34773.221366,3.532020,7.736611e+05,14.994644,5.686720,19709.866716,1.585519e+06,24.159232,66.348148
min,2000.000000,1.252269,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,1.000000e+01,0.000000,-62.075920,111.927225,2.100000e+01,-40.900557,-175.198242
25%,2005.000000,59.800890,23.175000,3.540000,2.600000e+05,6.515000,0.290000,0.000000,0.040000,2.877847,3116.737300,3.170000,2.020000e+03,2.137095,1.383302,1337.813437,2.571300e+04,3.202778,-11.779889
50%,2010.000000,98.361570,83.150000,32.910000,5.665000e+06,23.300000,2.970000,0.000000,1.470000,27.865068,13120.570000,4.300000,1.050000e+04,6.290766,3.559855,4578.633208,1.176000e+05,17.189877,19.145136
75%,2015.000000,100.000000,100.000000,112.210000,5.534750e+07,55.245000,26.837500,0.000000,9.600000,64.403792,33892.780000,6.027500,6.058000e+04,16.841638,5.830099,15768.615365,5.131200e+05,38.969719,46.199616
max,2020.000000,100.000000,100.000000,3060.190000,5.202310e+09,96.040000,5184.130000,809.410000,2184.940000,100.000010,262585.700000,32.570000,1.070722e+07,86.836586,123.139555,123514.196700,9.984670e+06,64.963051,178.065032

1) Mean:2010.038367	78.933702	63.255287	113.137498	9.422400e+07	32.638165	70.365003	13.450190	23.968010	36.801182	25743.981745	5.307345	1.598665e+05	11.986707	3.441610	13283.774348	6.332135e+05	18.246388	14.822695

2) Min: 2000.000000	1.252269	0.000000	0.000000	0.000000e+00	0.000000	0.000000	0.000000	0.000000	0.000000	0.000000	0.110000	1.000000e+01	0.000000	-62.075920	111.927225	2.100000e+01	-40.900557	-175.198242
Max: 2020.000000	100.000000	100.000000	3060.190000	5.202310e+09	96.040000	5184.130000	809.410000	2184.940000	100.000010	262585.700000	32.570000	1.070722e+07	86.836586	123.139555	123514.196700	9.984670e+06	64.963051	178.065032

In [ ]:
# Typing
# "Entity" before
# "Year" before
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   object
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   float64
 19  Latitude                                                          3648 non-null   float64
 20  Longitude                                                         3648 non-null   float64
dtypes: float64(18), int64(1), object(2)
memory usage: 598.8+ KB

In [ ]:
# "Entity" after
# "Year" after
df.Entity = df.Entity.astype('category')
df.Year = df.Year.astype('float64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   category
 1   Year                                                              3649 non-null   float64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   float64
 19  Latitude                                                          3648 non-null   float64
 20  Longitude                                                         3648 non-null   float64
dtypes: category(1), float64(19), object(1)
memory usage: 582.9+ KB

В своём датасете я выделю три признака: категориальный (Entity отвечает за страну), числовой порядковый (Year отвечает за год), числовой количественный (primary energy consumption per capita и другие)

In [ ]:
# Filtration 1
df[df["Year"] == 2000]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000.0,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.640000,760.0,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
21,Albania,2000.0,100.000000,38.2,NaN,NaN,NaN,0.14,0.0,4.55,...,9029.43750,4.130000,3170.0,NaN,6.946217,1126.683340,105,28748.0,41.153332,20.168331
42,Algeria,2000.0,98.973100,97.1,8.91,NaN,0.43,23.84,0.0,0.05,...,9746.52400,4.180000,80050.0,0.053235,3.800000,1765.027146,18,2381741.0,28.033886,1.659626
63,Angola,2000.0,24.212744,41.1,14.37,NaN,73.44,0.50,0.0,0.90,...,1979.25620,3.680000,16200.0,NaN,3.054624,556.838632,26,1246700.0,-11.202692,17.873887
84,Antigua and Barbuda,2000.0,97.689260,100.0,0.00,NaN,0.00,0.14,0.0,0.00,...,28457.22300,3.130000,330.0,NaN,6.203431,10872.292950,223,443.0,17.060816,-61.796428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3544,Uzbekistan,2000.0,99.593270,83.6,64.43,NaN,0.72,38.51,0.0,5.82,...,24053.54700,28.200000,123810.0,2.899541,3.835000,558.226802,79,447400.0,41.377491,64.585262
3565,Vanuatu,2000.0,22.143080,15.9,3.24,NaN,48.65,0.04,0.0,0.00,...,1988.27890,3.660000,90.0,NaN,5.924809,1470.635870,25,12189.0,-15.376706,166.959158
3586,Yemen,2000.0,49.187256,55.7,0.00,1480000.0,0.95,3.21,0.0,0.00,...,3228.21040,2.823132,NaN,NaN,NaN,NaN,56,527968.0,15.552727,48.516388
3607,Zambia,2000.0,16.700000,13.8,173.03,10000.0,89.98,0.07,0.0,7.69,...,2951.36720,12.770000,1810.0,NaN,3.897323,345.689621,25,752618.0,-13.133897,27.849332
3628,Zimbabwe,2000.0,33.654890,33.5,61.42,40000.0,69.26,3.30,0.0,3.44,...,4919.52250,9.390000,13700.0,NaN,-3.059190,563.057504,38,390757.0,-19.015438,29.154857

In [ ]:
# Filtration 2
df[df["Renewable-electricity-generating-capacity-per-capita"] - 10 > 0]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
58,Algeria,2016.0,99.350250,99.6,11.88,160000.0,0.08,66.43,0.0,0.34,...,15295.1430,4.85,154910.00370,0.145807,3.200000,3946.452447,18,2381741.0,28.033886,1.659626
59,Algeria,2017.0,99.635490,99.6,16.02,10000.0,0.14,70.86,0.0,0.64,...,15164.0000,4.93,158339.99630,0.247018,1.300000,4109.698217,18,2381741.0,28.033886,1.659626
60,Algeria,2018.0,99.697840,99.6,16.25,50000.0,0.19,71.32,0.0,0.78,...,15971.0840,5.19,165539.99330,0.287679,1.100000,4142.018558,18,2381741.0,28.033886,1.659626
61,Algeria,2019.0,99.500000,99.7,15.93,60000.0,0.16,75.85,0.0,0.84,...,16259.0530,5.32,171250.00000,0.294747,1.000000,3989.668276,18,2381741.0,28.033886,1.659626
62,Algeria,2020.0,99.804130,99.7,15.64,NaN,NaN,72.01,0.0,0.72,...,14933.8070,NaN,NaN,0.297899,-5.100000,3306.858208,18,2381741.0,28.033886,1.659626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016.0,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.6802,10.00,11020.00046,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017.0,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.0115,9.51,10340.00015,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018.0,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.9858,9.83,12380.00011,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019.0,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.6553,10.47,11760.00023,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020.0,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.1318,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [ ]:
# Filtration 3
df[df["Latitude"] != 33.93911]

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
21,Albania,2000.0,100.000000,38.2,NaN,NaN,NaN,0.14,0.0,4.55,...,9029.4375,4.13,3170.000000,NaN,6.946217,1126.683340,105,28748.0,41.153332,20.168331
22,Albania,2001.0,100.000000,40.5,NaN,NaN,NaN,0.13,0.0,3.52,...,8635.5320,3.89,3230.000000,NaN,8.293313,1281.659826,105,28748.0,41.153332,20.168331
23,Albania,2002.0,100.000000,43.2,NaN,NaN,NaN,0.16,0.0,3.48,...,9443.5550,4.10,3759.999990,NaN,4.536524,1425.124219,105,28748.0,41.153332,20.168331
24,Albania,2003.0,100.000000,46.4,NaN,NaN,NaN,0.10,0.0,5.12,...,10756.6120,3.80,4070.000172,NaN,5.528637,1846.120121,105,28748.0,41.153332,20.168331
25,Albania,2004.0,100.000000,49.0,NaN,NaN,NaN,0.13,0.0,5.41,...,11586.9510,3.96,4250.000000,NaN,5.514668,2373.581292,105,28748.0,41.153332,20.168331
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016.0,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.6802,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017.0,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.0115,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018.0,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.9858,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019.0,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.6553,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020.0,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.1318,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [ ]:
# Group mean
df.groupby('Entity', as_index = False).mean()

<ipython-input-12-1709346f63a1>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Entity', as_index = False).mean()

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Land Area(Km2),Latitude,Longitude
0,Afghanistan,2010.0,52.520488,19.802381,8.581429,3.296947e+07,25.6805,0.189524,0.0,0.740952,78.872636,697.268136,2.039000,4073.000025,NaN,6.163893,439.055765,652230.0,33.939110,67.709953
1,Albania,2010.0,99.981429,63.592857,NaN,NaN,NaN,0.048571,0.0,5.184286,98.855430,11353.520929,3.177500,4303.000004,NaN,3.859305,3623.224775,28748.0,41.153332,20.168331
2,Algeria,2010.0,99.108146,98.904762,9.390000,5.056250e+05,0.2870,46.895714,0.0,0.365238,0.742125,12925.532952,4.498500,119921.000066,0.185239,2.885714,3787.817377,2381741.0,28.033886,1.659626
3,Angola,2010.0,35.138564,44.933333,43.951429,9.525000e+06,57.6970,2.040476,0.0,4.420952,68.980548,3102.008457,2.896500,21689.499863,NaN,4.945895,2982.568601,1246700.0,-11.202692,17.873887
4,Antigua and Barbuda,2010.0,98.823761,100.000000,22.455238,9.700000e+06,0.2005,0.271429,0.0,0.002857,0.861557,32065.486190,3.624000,512.999998,NaN,1.515946,13555.401528,443.0,17.060816,-61.796428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,Uzbekistan,2010.0,99.848840,84.976190,61.972381,5.868556e+07,1.2385,43.476667,0.0,6.438095,12.974661,19346.599286,15.948500,118427.000704,3.192610,6.253772,1438.250604,447400.0,41.377491,64.585262
172,Vanuatu,2010.0,41.269784,12.050000,19.339524,5.694000e+06,43.6560,0.046667,0.0,0.008095,11.904762,2471.556643,3.516500,122.999999,NaN,2.441195,2458.898510,12189.0,-15.376706,166.959158
173,Yemen,2010.0,60.928522,59.290476,1.672381,1.059562e+07,1.3115,4.907619,0.0,0.091905,2.593720,2998.960281,3.067611,NaN,NaN,NaN,NaN,527968.0,15.552727,48.516388
174,Zambia,2010.0,27.753585,14.471429,146.577619,1.881594e+08,86.8955,0.492381,0.0,10.701429,96.479406,3027.719648,9.181500,3559.000016,NaN,5.442444,1144.799404,752618.0,-13.133897,27.849332
175,Zimbabwe,2010.0,39.172120,30.930952,66.068571,2.651154e+07,79.1500,3.229048,0.0,5.007143,60.849178,3825.827057,11.474762,11040.000110,NaN,0.132669,916.669430,390757.0,-19.015438,29.154857

In [ ]:
# Genius (aggregation without pandas)
import csv

In [ ]:

with open("/content/dataset/global-data-on-sustainable-energy.csv") as f:
    reader = csv.reader(f)
    headers = next(reader) #first string
    aggregate_data = {}

    for row in reader: # run for each string of csv-file
        # Проверяем, если количество значений в строке совпадает с количеством колонок
        if len(row) == len(headers): # if num znach == quantity kolonok
            for i in range(len(row)): # run for each znach from string
                # number or categorical
                try:
                    # in number
                    value = float(row[i])

                    # if znach - number sign, find categorical sign
                    category = headers[i]

                    # category in slovar ? add number sign
                    if category in aggregate_data:
                        aggregate_data[category].append(value)
                    # no category - create new with number sign
                    else:
                        aggregate_data[category] = [value]
                except ValueError:
                    # znach no number - skip
                    continue
        else:
            continue

# Вычисляем медиану и среднее значение для каждой категории
for category, values in aggregate_data.items(): #  items() -- get pair key - meaning
    median = sorted(values)[len(values) // 2]
    mean = sum(values) / len(values)
    print(f'Category: {category}')
    print(f'Median: {median}')
    print(f'Mean: {mean}')
    print('---')

Category: Year
Median: 2010.0
Mean: 2010.0383666758016
---
Category: Access to electricity (% of population)
Median: 98.36157
Mean: 78.93370216207742
---
Category: Access to clean fuels for cooking
Median: 83.2
Mean: 63.255287356321816
---
Category: Renewable-electricity-generating-capacity-per-capita
Median: 32.94
Mean: 113.13749816041195
---
Category: Financial flows to developing countries (US $)
Median: 5670000.0
Mean: 94224000.0
---
Category: Renewable energy share in the total final energy consumption (%)
Median: 23.3
Mean: 32.63816497829229
---
Category: Electricity from fossil fuels (TWh)
Median: 2.97
Mean: 70.3650027563395
---
Category: Electricity from nuclear (TWh)
Median: 0.0
Mean: 13.450190178824874
---
Category: Electricity from renewables (TWh)
Median: 1.47
Mean: 23.968009922822443
---
Category: Low-carbon electricity (% electricity)
Median: 27.865068
Mean: 36.8011818698508
---
Category: Primary energy consumption per capita (kWh/person)
Median: 13120.57
Mean: 25743.981745042187
---
Category: Energy intensity level of primary energy (MJ/$2017 PPP GDP)
Median: 4.3
Mean: 5.307345058890176
---
Category: Value_co2_emissions_kt_by_country
Median: 10500.0
Mean: 159866.46268574576
---
Category: Density\n(P/Km2)
Median: 83.0
Mean: 141.03048264182897
---
Category: Land Area(Km2)
Median: 117600.0
Mean: 633213.4893092106
---
Category: Latitude
Median: 17.189877
Mean: 18.24638776044415
---
Category: Longitude
Median: 19.145136
Mean: 14.82269454217112
---
Category: gdp_per_capita
Median: 4578.633208
Mean: 13283.774347967446
---
Category: gdp_growth
Median: 3.561582191
Mean: 3.441610056684865
---
Category: Renewables (% equivalent primary energy)
Median: 6.291511
Mean: 11.98670682809521
---